### ISSUE TITLE
At: Atom startup: Failed to load snippets from 'C:\Users\Portatil.atom\packages\materialize-css\snippets\html.cson'

### ISSUE THREAD

**Issue by antonioortizdev** [ayinloya/Materialize-Css-Atom-Snippets#6] opened 2018-05-31 09:13 UTC
Hi, I have this issue! 
Failed to load snippets from 'C:\Users\Portatil.atom\packages\materialize-css\snippets\html.cson'

C:\Users\Totti\.atom\packages\materialize-css\snippets\html.cson: Duplicate key 'Materialize basic pagination'

This error happens everytime i start atom.

**Comment by antonioortizdev** [comment] 2018-05-31 09:17
Hi Again! Looks like i fixed it by changing this:
![2018-05-31 11_15_07-html cson c__users_portatil_ atom_packages_materialize-css atom](https://user-images.githubusercontent.com/25205674/40773743-19d0425c-64c4-11e8-9d92-3226ee82f79d.png)
To this:
![2018-05-31 11_17_11-html cson c__users_portatil_ atom_packages_materialize-css atom](https://user-images.githubusercontent.com/25205674/40773802-3cdab9b2-64c4-11e8-97a0-ac9ce353da4e.png)

**Comment by ayinloya** [comment] 2018-05-31 09:24
I'll fix this over the weekend, thanks for the screenshot

**Comment by sahalmhasa** [comment] 2018-06-01 03:28
@Totti619 @ayinloya 

man, it doesn't work. the same popup showed again after changed to this

![materialize-cson](https://user-images.githubusercontent.com/24928407/40819668-dfe2d378-6579-11e8-8c7a-567ad1a5c1f1.png)

**Comment by devsware** [comment] 2018-06-01 10:16
I confirm the same problem on Linux Mint.
I've checked the same lines highlighted by @Totti619 but in my case the lines were already correct (as in the second image).

The error popup indicates an unexpected column, but unfortunately no info about the line where it occurs are given (see image below)

![materialize-css-problem](https://user-images.githubusercontent.com/7092708/40835961-581ee73a-6595-11e8-819d-352e7b5dbc68.jpg)

**Comment by ayinloya** [comment] 2018-06-01 14:29
@devsware @sahalmhasa a patch has been pushed to fix this issue, please install the update, and let me know

**Comment by devsware** [comment] 2018-06-01 15:08
@ayinloya just updated and the error is gone.
Everything works as expected and the prefixes are correctly expanded.

Thank you! :)

**Comment by ayinloya** [comment] 2018-06-01 15:11
Great, I'll be closing this issue then

**Closed as completed by ayinloya** 2018-06-01 15:11 UTC

**Comment by sahalmhasa** [comment] 2018-06-08 12:14
@ayinloya just updated and the problem is gone. 
it works  Thank you 👍
